#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "$0")" || exit 1; pwd -P)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." || exit 1; pwd -P)"
LIBS_DIR="${ROOT_DIR}/lib"

function apply_default_settings {
   "${SCRIPT_DIR}"/system_settings/apply.sh
}

function revert_default_settings {
  "${SCRIPT_DIR}"/system_settings/restore_default.sh
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  printf "Loaded: %s\n" "${BASH_SOURCE[0]}"
else
  printf "Run directly: %s\n" "${BASH_SOURCE[0]}"
  apply_default_settings
fi
