#!/usr/bin/env bash

function apply_default_settings {
  printf "NOT IMPLEMENTED YET\n"
}

function revert_default_settings {
  printf "NOT IMPLEMENTED YET\n"
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  printf "Loaded: %s\n" "${BASH_SOURCE[0]}"
else
  apply_default_settings
fi
