#!/usr/bin/env bash

# Copied from:
# https://github.com/bkuhlmann/mac_os/blob/566b9d871ebb9fa59bf9407ac568ac2d16d7aa06/bin/install_dev_tools

function install_xcode_cli_tools {
  printf "Installing Xcode CLI tools...\n"

  xcode-select --install

  install_status=$?
  if [ $install_status -ne 0 ]
  then
    RED='\033[0;31m'; NC='\033[0m' # No Color
    echo
    printf "${RED}Command failed, most probably Xcode CLI tools already installed${NC}\n"
    return
  fi

  printf "%s\n" "💡 ALT+TAB to view and accept Xcode license window."
  read -p "Have you completed the Xcode CLI tools install (y/n)? " xcode_response
  if [[ "$xcode_response" != "y" ]]; then
    printf "ERROR: Xcode CLI tools must be installed before proceeding.\n"
    exit 1
  fi

  if [[ "$(/usr/bin/arch)" == "arm64" ]]; then
    softwareupdate --install-rosetta --agree-to-license
  fi
}

function uninstall_xcode_cli_tools {
  printf "There is no option to uninstall Xcode\n"
}

printf "Loaded: %s\n" "${BASH_SOURCE[0]}"
