#!/usr/bin/env bash

# shellcheck disable=SC2059

# Warning!
# Have a look: https://stackoverflow.com/a/67043934
# Actually I had this issue, and same as there, running Homebrew through NordVPN did the job.

function install_homebrew {
  if ! command -v brew > /dev/null; then
#    /bin/bash -c "$(curl --location --fail --silent --show-error https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  else
    RED='\033[0;31m'; NC='\033[0m' # No Color
    printf "${RED}Homebrew already installed${NC}\n"
  fi
}

function remove_homebrew {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  printf "Loaded: %s\n" "${BASH_SOURCE[0]}"
else
  install_homebrew
fi
