#!/usr/bin/env bash

function install_homebrew_formulas {
  printf "Installing Homebrew formulas...\n"
  set -x
  brew install mas  # tool to install apps from App Store

  brew install readline
  brew install tmux
  brew install mc
  brew install tree
  brew install wget
  brew install curl
  brew install vim
  brew install htop

  brew install zsh

  brew install jq
  brew install pv  # data's progress through a pipe

  brew install git
  brew install git-lfs
  brew install git-gui
  brew install git-cola

  set +x
  printf "Installing Homebrew formulas... DONE\n"
}

function remove_homebrew_formulas {
  printf "NOT IMPLEMENTED YET\n"
  exit 1
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  printf "Loaded: %s\n" "${BASH_SOURCE[0]}"
else
  install_homebrew_formulas
fi
