#!/usr/bin/env bash

function install_homebrew_casks {
  printf "NOT IMPLEMENTED YET\n"
}

function remove_homebrew_casks {
  printf "NOT IMPLEMENTED YET\n"
}

printf "Loaded: %s\n" "${BASH_SOURCE[0]}"
