#!/usr/bin/env bash

# Installs App Store software.

function install_app_store_apps {
  printf "Installing App Store software...\n"

  # 1Password
  mas install 443987910

  # NordVPN
  mas install 1116599239

  printf "Installing App Store software... DONE\n"
}

function uninstall_app_store_apps {
  printf "NOT IMPLEMENTED YET"
  exit 1
}

printf "Loaded: %s\n" "${BASH_SOURCE[0]}"
