#!/usr/bin/env bash

function install_dotfiles {
  git clone --recursive https://github.com/rynkowski/dotfiles "$HOME"/.dotfiles
  . "$HOME"/.dotfiles/install.sh
}

function uninstall_dotfiles {
  printf "NOT IMPLEMENTED YET"
  exit 1
}

printf "Loaded: %s\n" "${BASH_SOURCE[0]}"
